HorizonAuth/mvcAuth2019/Controllers/FilesUploadController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using HorizonRE.Models;
using mvcAuth2019.Models;

namespace HorizonRE.Controllers
{

    [Authorize(Roles = RoleName.EMPLOYEE)]
    public class FilesUploadController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FilesUpload
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file, ImageFile image)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (file.ContentLength > 0)
                    {
                        int imgFileLimit = 5242880;

                        if (file.ContentLength <= imgFileLimit)
                        {
                            string fileName = Path.GetFileName(file.FileName);
                            string filePath = Path.Combine(Server.MapPath("~/TempFiles"), fileName);

                            //image type validation
                            System.Drawing.Image img = System.Drawing.Image.FromStream(file.InputStream);

                            if (ImageFormat.Jpeg.Equals(img.RawFormat) ||
                                ImageFormat.Gif.Equals(img.RawFormat) ||
                                ImageFormat.Bmp.Equals(img.RawFormat) ||
                                ImageFormat.Png.Equals(img.RawFormat) ||
                                ImageFormat.Tiff.Equals(img.RawFormat)

                                )
                            {
                                if (System.IO.File.Exists(filePath))
                                {
                                    Random rnd = new Random();
                                    string extractName = fileName.Substring(0, fileName.IndexOf("."));
                                    string fileExt = fileName.Substring(fileName.IndexOf("."));
                                    fileName = extractName + "_" + rnd.Next(1, 999999) + fileExt;
                                    filePath = Path.Combine(Server.MapPath("~/TempFiles"), fileName);
                                }


                                file.SaveAs(filePath);


                                string imageRelativePath = $@"/Content/Files/{fileName}";


                                string imageDesc = image.ImageDescription;
                                image.ImageName = fileName;
                                image.AltText = imageDesc;
                                image.Path = imageRelativePath;
                                image.UploadDate = DateTime.Today;
                                //@TODO: REMOVE EMPLOYEE ID 
                                //!REMOVE
                                var currentEmployee = db.Employees.Where(e => e.OfficeEmail == User.Identity.Name).FirstOrDefault();

                                if (currentEmployee != null)
                                {
                                    image.EmployeeId = currentEmployee.EmployeeId;
                                }
                                else
                                {
                                    image.EmployeeId = 1;
                                }


                                image.Approved = false;
                                image.ListingId = null;


                                db.Images.Add(image);
                                db.SaveChanges();

                                ViewBag.Msg = "Uploaded file was saved successfully";

                                return View();
                            }
                            else
                            {
                                ViewBag.Msg = "Not a valid type of file";
                                return View();
                            }
                        }
                        else
                        {
                            ViewBag.Msg = "File size was exceeded";
                            return View();
                        }
                    }

                    return View();
                }
                catch (DbUpdateException ex)
                {
                    ViewBag.Msg = ex.Message + " " + ex.GetType().ToString();
                    return View();
                }
                catch (Exception ex)
                {
                    ViewBag.Msg = ex.Message + " " + ex.GetType().ToString();
                    return View();
                }
            }
            else
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult MoveFile()
        {
            getImages();
            return View();
        }

        [HttpPost]
        public ActionResult MoveFile(List<string> fileList)
        {
            ViewBag.fileName = fileList[0];

            //redirect to a diff view
            return View("MoveFileDisplay");
        }


        public ActionResult ApproveFile(string fileToApprove, string approve)
        {
            if (!string.IsNullOrEmpty(fileToApprove) && approve == "Yes")
            {
                string sourceFile = Server.MapPath("/TempFiles/" + fileToApprove);
                string destinationFile = Server.MapPath("/Content/Files/") + fileToApprove;


                if (!System.IO.File.Exists(destinationFile))
                {

                    //1. Get file record from db

                    ImageFile img = db.Images.Where(im => im.ImageName == fileToApprove).SingleOrDefault();


                    if (img != null)
                    {

                        if (img.Employee.OfficeEmail != User.Identity.Name)
                        {
                            //2. Set approved to true 
                            img.Approved = true;

                            db.Entry(img).State = EntityState.Modified;
                            db.SaveChanges();

                            System.IO.File.Move(sourceFile, destinationFile);
                            ViewBag.Msg = "File has been approved";
                        }
                        else
                        {
                            ViewBag.Msg = "You cannot approve your own images";
                        }


                    }






                }
                else
                {
                    ViewBag.Msg = "File with that name already exists";
                }
            }
            else
            {
                if(fileToApprove != null)
                {
                    string sourceFile = Server.MapPath("~/TempFiles/" + fileToApprove);
                    string destinationFile = Server.MapPath("~/FilesToDelete/") + fileToApprove;

                    System.IO.File.Move(sourceFile, destinationFile);
                    //if you want tot delete
                    System.IO.File.Delete(sourceFile);

                    ViewBag.Msg = "File has been removed";
                }
                else
                {
                    getImages();
                    return View("MoveFile");
                }
               
            }

            return View("MoveFileDisplay");
        }

        private void getImages()
        {
            //get the images from the system
            string folderPath = Server.MapPath("~/TempFiles");

            if (Directory.Exists(folderPath))
            {
                //create an arry of the files found in the directory at the specified path
                string[] fileEntries = Directory.GetFiles(folderPath);

                //process the list of files found in the directory
                string fileName = null;

                string[] fileList = new string[fileEntries.Count()];
                int i = 0;

                foreach (string file in fileEntries)
                {
                    fileName = Path.GetFileName(file);
                    fileList[i++] = fileName;
                }


                //create select list form array
                SelectList list = new SelectList(fileList);
                ViewBag.fileList = fileList.Length > 0 ? list : null;
            }
            else
            {
                ViewBag.Msg = "Directory doesn't exist";
            }
        }
    }
}

HorizonAuth/mvcAuth2019/Views/FilesUpload/Index.cshtml
@model HorizonRE.Models.ImageFile
@{
    ViewBag.Title = "Files Upload";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container mt-md-5 mt-sm-0">

    <h2 class="display-4 mb-4">Upload Photos</h2>

    <div class="row ml-2">
        
        <div class="col-md-10 ">
            @using (Html.BeginForm("Index", "FilesUpload", FormMethod.Post,
                new {enctype = "multipart/form-data", @class = "w-100", id="form"}))
            {
                <p class="mt-3">Please select photos to upload</p>

                <div class="form-group">
                    <div class="custom-file">
                        @Html.TextBox("file", "", new {type = "file", @class = "custom-file-input", required = true, id = "validatedCustomFile" })
                        <label class="custom-file-label" for="validatedCustomFile">Choose file...</label>
                        @Html.ValidationMessage("file", "", new {@class = "text-danger"})
                    </div>
                </div>
                <div class="form-group">
                    @Html.TextAreaFor(i => i.ImageDescription, new {@class = "form-control", style = "resize:none", rows = "5", id="textarea"})
                    @Html.ValidationMessageFor(i => i.ImageDescription, "", new {@class = "text-danger"})
                </div>

                <button type="submit" class="btn btn-primary mb-4">Save</button>

            }
            
            <p class="mb-3 text-success @(!string.IsNullOrEmpty(ViewBag.Msg) ? "show" : "hide")">
                @ViewBag.Msg
            </p>

            @Html.ActionLink("Approve Photos", "MoveFile")

        </div>

       
    </div>
</div>


<script src="~/Scripts/jquery-3.4.1.js"></script>
<script>
    $('.custom-file-input').on('change',function(){
        //get the file name
        var fileName = $(this).val();
        fileName = fileName.replace('C:\\fakepath\\', " ");
        //replace the "Choose a file" label
        $(this).next('.custom-file-label').html(fileName);
    })

    

    document.addEventListener('DOMContentLoaded',
        () => {
            document.querySelector('#textarea').value = "";
        }, false);
   
</script>

HorizonAuth/mvcAuth2019/Views/FilesUpload/MoveFile.cshtml
@{
    ViewBag.Title = "MoveFile";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container mt-md-5 mt-sm-0">
    <h2 class="display-4 mb-4">Approve Photos</h2>
    @if (ViewBag.fileList != null)
    {
        <p>Please select a photo to approve</p>
    }
    else
    {
        <p>No photos to approve</p>
    }
    <!--TODO : NEED TO HIDE WHEN NO Photos to approve-->

    @using (Html.BeginForm("MoveFile", "FilesUpload", FormMethod.Post))
    {
        <div class="form-row">


            @if (ViewBag.fileList != null)
            {

                <div class="form-group col-md-6">
                    @Html.DropDownList("fileList", ViewBag.fileList as SelectList, new { @class = "form-control" })
                </div>
                <div class="form-group col-md-3">
                    <input type="submit" value="Display" class="btn btn-primary" />
                </div>
            }



        </div>
    }

    @ViewBag.Msg

  
</div>

HorizonAuth/mvcAuth2019/Views/FilesUpload/MoveFileDisplay.cshtml
@{
    ViewBag.Title = "MoveFileDisplay";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container mt-md-5 mt-sm-0">
    <h2 class="display-4 mb-4">Approve Photos</h2>

    @if (string.IsNullOrEmpty(ViewBag.Msg))
    {
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img src="~/TempFiles/@ViewBag.fileName" alt="@ViewBag.fileName"
                         class="card-img-top" />
                </div>
            </div>

            <div class="col-md-6">
                @using (Html.BeginForm("ApproveFile", "FilesUpload", FormMethod.Post))
                {
                    <input type="hidden" name="fileToApprove" value="@ViewBag.fileName" />
                    <h4 class="mb-3">Approve:</h4>
                    <div class="form mb-3">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="approve" value="Yes">
                            <label class="form-check-label" for="Yes">
                                Yes
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="approve" value="No">
                            <label class="form-check-label" for="No">
                                No
                            </label>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
                }
            </div>

        </div>
    }


    <p class="h3 @(!string.IsNullOrEmpty(ViewBag.Msg) ? "show" : "hide")">@ViewBag.Msg</p>

    @Html.ActionLink("<-Back to Approve photos", "MoveFile", "FilesUpload")

</div>