HorizonAuth/mvcAuth2019/Controllers/ListingsManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HorizonRE.Models;
using HorizonRE.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using mvcAuth2019;
using mvcAuth2019.Models;
using PagedList;

namespace HorizonRE.Controllers
{


    [Authorize]
    public class ListingsManagementController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        // GET: ListingsManagement
        [Authorize(Roles = RoleName.EMPLOYEE)]
        public ActionResult Index(int? customerId, string search = null, string currentSearch = null)
        {


            var viewModel = new ListingCustomerAgentView();


            if (string.IsNullOrEmpty(search))
            {
                search = currentSearch;
            }


            if (search != null)
            {
                viewModel.Customers = db.Customers.Where(cx => cx.FirstName.ToLower().Contains(search.ToLower()) || cx.LastName.ToLower().Contains(search.ToLower()) || cx.Phone.Replace(" ", "").Replace("(", "").Replace(")", "").Replace("-", "").Contains(search));


            }









            if (customerId != null)
            {
                ViewBag.SelectedCustomer = customerId.Value;

                viewModel.Listings = db.Listings.Include(l => l.Employee);

                viewModel.Listings = viewModel.Customers
                    .Where(c => c.CustomerId == customerId.Value).Single().Listings;


                if (viewModel.Listings.Count() == 0)
                {
                    ViewBag.ShowMsg = true;
                }

            }

            if (customerId == null)
            {
                ViewBag.ShowMsg = false;
            }

            //!When customer is retrieved retrieve all his listings 
            //viewModel.Listings = viewModel.Customers.Where(c => c.CustomerId == customerId.Value).Single().Listings;


            ViewBag.CurrentSearch = search;


            return View(viewModel);
        }

        // GET: ListingsManagement/Details/5
        [Authorize(Roles = RoleName.EMPLOYEE)]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Listing listing = db.Listings.Find(id);
            if (listing == null)
            {
                return HttpNotFound();
            }
            return View(listing);
        }

        // GET: ListingsManagement/Create
        [HttpGet]
        [Authorize(Roles = RoleName.EMPLOYEE)]
        public ActionResult Create(int? custId)
        {

            if (custId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var listing = new Listing();
            listing.Features = new List<Feature>();


            //GET FEATURES 

            ViewBag.CityAreas = new SelectList(db.CityAreas, "AreaId", "Name");
            ViewBag.Countries = new SelectList(db.Countries, "CountryId", "Name");
            ViewBag.Provinces = new SelectList(db.Provinces.Where(p => p.CountryId == 1), "ProvinceId", "Name");

            //ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "FirstName");
            ViewBag.Employees = new SelectList(db.Employees, "EmployeeId", "FullName");

            ViewBag.SelectedCustomer = custId;

            PopulateFeatures(listing);

            return View();
        }



        // GET: ListingsManagement/Create
        [HttpPost]
        [Authorize(Roles = RoleName.EMPLOYEE)]
        public ActionResult Create(Listing listing, HttpPostedFileBase[] selectedImages,
            string[] selectedFeature, string SelectedCustomer)
        {
            int customerId = int.Parse(SelectedCustomer);

            listing.CustomerId = customerId;

            if (selectedImages.Count() > 7)
            {

                ViewBag.Error = "You can only select no more than 7 images for a property";

                //ViewBag.CityAreas = new SelectList(db.CityAreas, "AreaId", "Name");

                //ViewBag.Employees = new SelectList(db.Employees, "EmployeeId", "FirstName");
                //PopulateFeatures(listing);
                //return View();
            }
            else
            {

                if (!listing.ContractSigned)
                {
                    listing.EmployeeId = null;
                }



                List<string> validImages = new List<string>();
                List<string> invalidImages = new List<string>();
                if (ModelState.IsValid)
                {   //iterating through multiple file collection   
                    foreach (HttpPostedFileBase file in selectedImages)
                    {
                        //Checking file is available to save.  
                        if (file != null)
                        {
                            var InputFileName = Path.GetFileName(file.FileName);


                            ImageFile img = db.Images
                                .Where(i => i.ImageName.ToLower()
                                .Contains(InputFileName.ToLower())
                                && i.Approved == true && i.ListingId == null).FirstOrDefault();


                            if (img != null)
                            {
                                validImages.Add(img.ImageName);
                            }
                            else
                            {
                                invalidImages.Add(file.FileName);
                            }


                        }

                        if (invalidImages.Count > 0)
                        {
                        

                            ViewBag.InvalidImagesError = invalidImages;

                        }

                    }

                    if (selectedFeature != null)
                    {
                        listing.Features = new List<Feature>();

                        foreach (var feat in selectedFeature)
                        {

                            var featureToAdd = db.Features.Find(int.Parse(feat));

                            listing.Features.Add(featureToAdd);
                        }
                    }


                    if (validImages.Count >= 0 && invalidImages.Count == 0)
                    {


                        //If contract is not signed
                        if (listing.ContractSigned)
                        {

                            listing.ListingStartDate = DateTime.Now.Date;
                            var todayPlus3Months = DateTime.Now.Date.AddMonths(3);
                            listing.ListingEndDate = todayPlus3Months;
                            listing.Status = "Active";
                        }
                        else
                        {
                            listing.ListingStartDate = null;
                            listing.ListingEndDate = DateTime.Now.Date.AddMonths(3);
                            listing.Status = "No contract";
                        }


                        int selectedCountry = Convert.ToInt32(Request.Form["Countries"].ToString());
                        int selectedProvince = Convert.ToInt32(Request.Form["Provinces"].ToString());

                        string countryName = db.Countries.Where(c => c.CountryId == selectedCountry).FirstOrDefault().Name;
                        string provinceName = db.Provinces.Where(c => c.ProvinceId == selectedProvince).FirstOrDefault().Name;



                        listing.Country = countryName;
                        listing.Province = provinceName;


                        db.Listings.Add(listing);
                        db.SaveChanges();


                        //get id of listing, to associate it with images
                        int id = listing.ListingId;

                        validImages.ForEach(img =>
                        {

                            ImageFile imageToUpdate = db.Images
                                .Where(im => im.ImageName.ToLower()
                                .Contains(img.ToLower())).FirstOrDefault();
                            imageToUpdate.ListingId = id;

                            db.Images.Attach(imageToUpdate);

                            db.Entry(imageToUpdate).Property(i => i.ListingId).IsModified = true;

                            // db.Entry(customer).State = EntityState.Modified;
                            db.SaveChanges();
                        });

                        return RedirectToAction("Index");
                    }
                }
            }




            PopulateFeatures(listing);
            ViewBag.CityAreas = new SelectList(db.CityAreas,
                "AreaId", "Name", listing.AreaId);

            ViewBag.Countries = new SelectList(db.Countries, "CountryId", "Name");
            ViewBag.Provinces = new SelectList(db.Provinces, "ProvinceId", "Name");

            ViewBag.Employees = new SelectList(db.Employees,
                "EmployeeId", "FullName", listing.EmployeeId);

            return View(listing);
        }


        private void PopulateFeatures(Listing listing)
        {

            var allFeattures = db.Features;
            var listingFeatures = db.Features.Select(f => f.Id).ToList();

            //GET ALL FEATURES THAT ASSOSIATED WITH THE CURRENT LISTING

            if (listing.ListingId != 0)
            {
                listingFeatures = new List<int>(listing.Features.Select(f => f.Id));
            }


            //!INIT LIST OF VIEWMODEL TO POPULATE PROPETIES
            var viewModel = new List<AssociatedFeatures>();

HorizonAuth/mvcAuth2019/Views/ListingsManagement/Create.cshtml
@model HorizonRE.Models.Listing

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container mt-md-5 mt-sm-0">
    <h2 class="text-center display-4 mb-4">Add Listing</h2>

    @if (ViewBag.Error != null)
    {
        <div class="alert alert-danger" role="alert">
            @ViewBag.Error
        </div>
    }


    @using (Html.BeginForm("Create", "ListingsManagement",
   FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.Hidden("Status", "No contract")
        @Html.Hidden("RenewNotificationSent", false)

        @Html.Hidden("SelectedCustomer", ViewBag.SelectedCustomer as string)

        <div class="form-row">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Country)
                @Html.DropDownList("Countries", ViewBag.Countries as SelectList, new { @class = "form-control" })

            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Province)
                @Html.DropDownList("Provinces", ViewBag.Provinces as SelectList, new { @class = "form-control" })
            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.StreetAddress)
                @Html.TextBoxFor(m => m.StreetAddress, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.StreetAddress, "", new { @class = "text-danger" })
            </div>


        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.City)
                @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.City, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.PostalCode)
                @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PostalCode, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.CityArea)
                @Html.DropDownListFor(m => m.AreaId,
                        ViewBag.CityAreas as SelectList, new { @class = "form-control" })
            </div>

        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Area)
                @Html.TextBoxFor(m => m.Area, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Area, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Bathrooms)
                @Html.TextBoxFor(m => m.Bathrooms, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Bathrooms, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Bedrooms)
                @Html.TextBoxFor(m => m.Bedrooms, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Bedrooms, "", new { @class = "text-danger" })

            </div>


        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                @Html.LabelFor(m => m.Price)
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })

            </div>
            <div class="form-group col-md-4">
                @Html.Label("Agent")
                @Html.DropDownListFor(m => m.EmployeeId,
                            ViewBag.Employees as SelectList, new { @class = "form-control" })
            </div>
            <div class="form-group col-md-4">
                @Html.Label("Contract")
                <div class="form-check">

                    @Html.CheckBoxFor(m => m.ContractSigned, new { @class = "form-check-input mt-3" })
                    @Html.LabelFor(m => m.ContractSigned, new { @class = "form-check-label my-2" })
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <div class="custom-file">
                    @Html.Label("Photos")
                    @Html.TextBox("selectedImages", "", new { @class = "form-control-file", type = "file",
                            multiple = "multiple", id = "files" })
                    <small class="form-text text-muted">
                        Select photos to associate with current
                        listing
                    </small>
                </div>
                @if (ViewBag.InvalidImagesError != null)
                {
                    <div class="alert alert-primary">
                        Following images cannot be added to this property
                        <br />

                        @{
                            List<string> errorMessages = ViewBag.InvalidImagesError;

                            foreach (var msg in errorMessages)
                            {
                                <p class="font-weight-bold mb-0">@msg</p>

                            }
                        }




                    </div>
                }

            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                @Html.Label("Features")
                @{
                    List<HorizonRE.ViewModel.AssociatedFeatures>
                        features = ViewBag.Features;


                    if (features != null)
                    {
                        int count = 0;
                        //FINISH

                        <div class="row justify-content-center">

                            @foreach (var f in features)
                            {
                                count++;

                                <div class="form-check mr-5 w-25 mb-3">
                                    <input type="checkbox" class="form-check-input"
                                           name="selectedFeature" value="@f.FeatureId" />
                                    <label class="form-check-label">@f.Title</label>
                                </div>
                            }

                        </div>
                    }

                }
            </div>
        </div>

        <input type="submit" value="Save" class="btn btn-primary my-4 float-right" />

    }
</div>






<script>
    //DropDowns
    var country = document.querySelector('#Countries');


    country.addEventListener('change',
        () => {

            var selectedCountryId = country.value;

            fetch(`/employee/GetProvincesByCountry?countryId=${selectedCountryId}`).then(jsn => jsn.json()).then(
                data => {
                    var listProvinces = document.querySelector("#Provinces");

                    listProvinces.innerHTML = "";

                    data.forEach(el => {

                        var option = document.createElement("option");
                        option.value = el.ProvinceId;
                        option.innerHTML = el.Name;
                        listProvinces.appendChild(option);
                    });


                }
            );

        });



</script>

HorizonAuth/mvcAuth2019/Views/ListingsManagement/CreateReport.cshtml
@model IEnumerable<HorizonRE.Models.Listing>
<link rel="stylesheet" media="print" title="Listings Report"
      type="text/css" href="~/Content/CSS/reportPrint.css">

@{
    ViewBag.Title = "CreateReport";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container mt-md-5 mt-sm-0">
    <div class="row">
        <div class="col-sm-8 col-lg-10">
            <h2 class="display-4 mb-4">Listings Report</h2>
            <p id="start-date" style="display:none"></p>
        </div>
    </div>

    <div class="row ml-2">

        @using (Html.BeginForm("CreateReport", "ListingsManagement", FormMethod.Get))
        {
            <div class="form-inline mb-3">

                @Html.TextBox("date", null,
                                new { @class = "form-control mr-4", type = "date", id = "start"})
                <input type="submit" value="Generate" class="btn btn-primary" />
            </div>
        }

    </div>
    <div class="row">
        @*@if (Model == null)
            {
                <p>Select date and click to generate</p>
            }*@
        @{
            List<HorizonRE.ViewModel.ListingReportViewModel>
            listingForReport = ViewBag.Report;

            if (listingForReport != null)
            {
                foreach (var item in listingForReport)
                {
                    if (item.listing.Count() > 0)
                    {
                        <h4 class="display-4" style="font-size: 2em">
                            @Html.DisplayFor(_ => item.Status)
                        </h4>

                        <table id="listings" class="table table-bordered table-hover mb-3">
                            <thead class="thead-dark" style="font-size:0.6em">
                                <tr>
                                    <th class="lead">Address</th>
                                    <th class="lead">Customer</th>
                                    <th class="lead">Customer phone</th>
                                    <th class="lead">Customer email</th>
                                    <th class="lead">Agent name</th>
                                    <th class="lead">Agent email</th>
                                    <th class="lead">Agent phone</th>
                                    <th class="lead">Contract expires</th>
                                </tr>
                            </thead>
                            <tbody style="font-size:0.8em">

                                @foreach (var listing in item.listing)
                                {
                                <tr>
                                    <td>@listing.StreetAddress @listing.City</td>
                                    <td>@listing.Customer.FullName</td>
                                    <td>@listing.Customer.Phone</td>
                                    <td>@listing.Customer.Email</td>

                                    @if (listing.Employee == null)
                                    {
                                        <td>No agent assigned</td>
                                        <td>No agent assigned</td>
                                        <td>No agent assigned</td>
                                    }
                                    else
                                    {
                                        <td>@listing.Employee.FullName</td>
                                        <td>@listing.Employee.OfficeEmail</td>
                                        <td>@listing.Employee.OfficePhone</td>
                                    }

                                    @if (listing.ContractSigned)
                                    {
                                        <td>@listing.ListingEndDate.ToShortDateString()</td>
                                    }
                                    else
                                    {
                                        <td>No contract signed</td>
                                    }

                                </tr>

                                }
                            </tbody>
                        </table>
                    }

                }

                <input type="button" id="print" class="btn btn-primary mb-3"
                       value="Print" onclick="printReport()">
            }
            else
            {
                <div class="alert alert-primary ml-2 mt-3" role="alert">
                    @ViewBag.Error
                </div>
            }

        }

    </div>

</div>

<script>
    function printReport() {


        let date = document.getElementById('start').getAttribute("value");
        let today = moment().format("YYYY-MM-DD");


        document.getElementById('start-date').textContent = `from ${date} to ${today}`;
        window.print();
    };
</script>

HorizonAuth/mvcAuth2019/Views/ListingsManagement/Index.cshtml
@model  HorizonRE.ViewModel.ListingCustomerAgentView


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}


<div class="container mt-md-5 mt-sm-0">
    <h2 class="display-4 mb-4">Listings</h2>
    <div class="row">
        <div class="col-md-6">
            <label>Find customer by name or phone:</label>
            @using (Html.BeginForm("Index", "ListingsManagement", FormMethod.Get))
            {

                <div class="input-group w-50">

                    @Html.TextBox("search", ViewBag.CurrentSearch as string, new { @class = "form-control", placeholder = "Search Customer"  })

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-primary">Search</button>
                    </div>

                </div>

            }

        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-12">
            @if (Model.Customers != null && Model.Customers.Count() > 0)
            {
                <table id="customers" class="table table-bordered table-hover mb-5">
                    <thead class="thead-dark">
                        <tr>
                            <th class="lead">Customer Name</th>
                            <th class="lead">Phone</th>
                            <th class="lead">Action</th>
                        </tr>
                    </thead>
                    <tbody>


                        @foreach (var customer in Model.Customers)
                        {

                            string selectedRow = "";

                            if (customer.CustomerId == ViewBag.SelectedCustomer)
                            {
                                selectedRow = "alert-info";
                            }

                            <tr class="@selectedRow">

                                <td>

                                    @Html.ActionLink($"{customer.FullName}",
                                            "Index", new { customerId = customer.CustomerId, search = ViewBag.CurrentSearch })
                                </td>
                                <td> @customer.Phone</td>
                                <td class="text-center">@Html.ActionLink("Add Listing", "Create", "ListingsManagement", new { custId = customer.CustomerId }, new { @class = "btn btn-success btn-sm" })</td>
                            </tr>
                        }


                    </tbody>
                </table>
            }
            else
            {
                if (@ViewBag.CurrentSearch != null && @ViewBag.CurrentSearch != "")
                {
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        Customer not found
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }


            }


            @if (Model.Listings != null && Model.Listings.Count() > 0)
            {
                <h3 class="display-4" style="font-size:1.5em"> Customer Listings </h3>

                <table class="table">
                    <tr>
                        <th>
                            Listing Id
                        </th>
                        <th>
                            Contract Start
                        </th>
                        <th>
                            Contract End
                        </th>
                        <th>
                            Address
                        </th>
                        <th>
                            Agent
                        </th>

                    </tr>
                    @foreach (var listing in Model.Listings)
                    {
                        <tr>
                            <td>
                                @listing.ListingId
                            </td>
                            @if (listing.ListingStartDate.HasValue)
                            {
                                <td>
                                    @listing.ListingStartDate.Value.ToShortDateString()
                                </td>
                            }
                            else
                            {
                                <td>
                                    No start date
                                </td>
                            }
                            <td>
                                @listing.ListingEndDate.ToShortDateString()
                            </td>
                            <td>
                                @listing.StreetAddress, @listing.City
                            </td>
                            @if (listing.Employee != null)
                            {
                                <td>
                                    @listing.Employee.FullName
                                </td>
                            }
                            else
                            {
                                <td>
                                    No assigned agent
                                </td>
                            }



                        </tr>

                    }

                </table>


            }



            @if (ViewBag.ShowMsg = true && ViewBag.SelectedCustomer != null && Model.Listings.Count() == 0)
            {

                <div class="alert alert-primary" role="alert">
                    No listings found
                </div>

            }
        </div>
    </div>

</div>

HorizonAuth/mvcAuth2019/Views/ListingsManagement/RenewContract.cshtml
@model HorizonRE.Models.Listing
@{
    ViewBag.Title = "RenewContract";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<div class="container mt-md-5 mt-sm-0">
    <div class="row mb-4">
        <div class="col-sm-8 col-lg-10">
            <h2 class="display-4 mb-4">Renew Contracts Area</h2>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-md-6">
            @using (Html.BeginForm("RenewContract", "ListingsManagement", FormMethod.Post))
            {

                <h2 class="display-4 mb-5" style="font-size:1.5em">
                    Notify customers about contract expiration
                </h2>

                <input type="submit" class="btn btn-primary"
                       value="Notify" />

                if (ViewBag.Msg != null) { 
                   <div class="alert alert-primary mt-3" role="alert">
                        @ViewBag.Msg
                   </div>
                }

            }
        </div>
        <div class="col-md-6">


            <h2 class="display-4 mb-5" style="font-size:1.5em">
                Renew contract for particular listing
            </h2>
            @using (Html.BeginForm("RenewContract", "ListingsManagement", FormMethod.Get))
            {
                <div class="input-group w-50">

                    @Html.TextBox("id", null, new { @class = "form-control",
                            placeholder = "Search listing" })
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-outline-primary">Search</button>
                    </div>
                </div>

                if (ViewBag.Message != null)
                {
                    <div class="alert alert-primary mt-3" role="alert">
                        @ViewBag.Message
                    </div>
                }
                if (ViewBag.Error != null)
                {
                    <div class="alert alert-primary mt-3" role="alert">
                        @ViewBag.Error
                    </div>
                }
            }

            @if (@Model != null)
            {
                using (Html.BeginForm("RenewContractManually", "ListingsManagement",
                    FormMethod.Post))
                {


                    <div class="card mt-4 w-50">

                        <div class="card-body">
                            <h5 class="card-title">Listing Info</h5>
                            @Html.HiddenFor(m => m.ListingId)

                            <p>Listing #@Model.ListingId</p>
                            <p>Address @Model.StreetAddress @Model.City</p>
                            <p>Expiration date @Model.ListingEndDate.ToShortDateString()</p>
                            <button type="submit"
                                    class="btn btn-outline-primary">
                                Renew Contract
                            </button>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>